kind: PersistentVolume
apiVersion: v1

metadata:
  name: mysql-pv

spec:
  storageClassName: standard

  capacity: 
    storage: 5Gi

  accessModes:
    - ReadWriteOnce

  hostPath:
    path: /mnt/data
