apiVersion: v1
kind: ResourceQuota
metadata:           
  name: dev-quota
  namespace: dev
spec:
  hard:            # Yani “Dev namespace” sirf 2 CPUs aur 4GB memory use kare.
    cpu: "2"
    memory: "4Gi"
